### PR TITLE
UP-4805: update jquery to version 1.11.0 and resource server to 1.0.44

### PR DESCRIPTION
**Pull request by JoshBrudnak**

### CODE REVIEW

**Comment by ChristianMurphy** [comment]
@Josh31415 SSP operates largely independent of uPortal.
@pspaude and @msultzaberger are the current maintainers of the SSP project.

**Comment by msultzaberger** [comment]
After pulling the merge request, I am seeing the following javascript error in the console when clicking on both Early Alert and Reports on the top menu:

fluid-all-1.4.0.min.js:33 Uncaught TypeError: Cannot read property 'msie' of undefined

**Comment by Josh31415** [comment]
Thanks @msultzaberger, I will look into it.

**Comment by pspaude** [comment]
SSP forked an older version of uPortal see: https://github.com/Jasig/SSP-Platform. SSP can't upgrade to the latest uPortal release due to a custom java message sharing layer and a customized personDirectory among other things that were inserted when SSP was created on the latest uP release years ago. These aren't deal breakers, SSP could upgrade, it just hasn't been funded by the community.

**Comment by ChristianMurphy** [comment]
:bell: @JoshBrudnak @msultzaberger Any update on this?

**Pull request closed without merging**
